[package]
name = "multiformat"
version = "0.1.0"
edition = "2018"
authors = ["Jack Maloney <git@jmmaloney4.xyz>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
